const kanjiData = [
    { kanji: "一", meaning: "one", onyomi: "いち (ichi)", kunyomi: "ひと-つ (hito-tsu)" },
    { kanji: "二", meaning: "two", onyomi: "に (ni)", kunyomi: "ふた-つ (futa-tsu)" },
    { kanji: "三", meaning: "three", onyomi: "さん (san)", kunyomi: "みっ-つ (mi-tsu)" },
    { kanji: "四", meaning: "four", onyomi: "し (shi)", kunyomi: "よん / よっ-つ (yon / yot-tsu)" },
    { kanji: "五", meaning: "five", onyomi: "ご (go)", kunyomi: "いつ-つ (itsu-tsu)" },
    { kanji: "六", meaning: "six", onyomi: "ろく (roku)", kunyomi: "むっ-つ (mut-tsu)" },
    { kanji: "七", meaning: "seven", onyomi: "しち (shichi)", kunyomi: "なな-つ (nana-tsu)" },
    { kanji: "八", meaning: "eight", onyomi: "はち (hachi)", kunyomi: "やっ-つ (yat-tsu)" },
    { kanji: "九", meaning: "nine", onyomi: "きゅう / く (kyuu / ku)", kunyomi: "ここの-つ (kokono-tsu)" },
    { kanji: "十", meaning: "ten", onyomi: "じゅう (juu)", kunyomi: "とお (too)" },
    { kanji: "人", meaning: "person", onyomi: "じん / にん (jin / nin)", kunyomi: "ひと (hito)" },
    { kanji: "今", meaning: "now", onyomi: "こん (kon)", kunyomi: "いま (ima)" },
    { kanji: "日", meaning: "day, sun", onyomi: "にち / じつ (nichi / jitsu)", kunyomi: "ひ / か (hi / ka)" },
    { kanji: "週", meaning: "week", onyomi: "しゅう (shuu)", kunyomi: "-" },
    { kanji: "月", meaning: "month, moon", onyomi: "げつ / がつ (getsu / gatsu)", kunyomi: "つき (tsuki)" },
    { kanji: "年", meaning: "year", onyomi: "ねん (nen)", kunyomi: "とし (toshi)" },
    { kanji: "中", meaning: "middle, inside", onyomi: "ちゅう (chuu)", kunyomi: "なか (naka)" },
    { kanji: "山", meaning: "mountain", onyomi: "さん (san)", kunyomi: "やま (yama)" },
    { kanji: "川", meaning: "river", onyomi: "せん (sen)", kunyomi: "かわ (kawa)" },
    { kanji: "左", meaning: "left", onyomi: "さ (sa)", kunyomi: "ひだり (hidari)" },
    { kanji: "右", meaning: "right", onyomi: "う / ゆう (u / yuu)", kunyomi: "みぎ (migi)" },
    { kanji: "大", meaning: "big", onyomi: "だい / たい (dai / tai)", kunyomi: "おお-きい (oo-kii)" },
    { kanji: "木", meaning: "tree, wood", onyomi: "もく / ぼく (moku / boku)", kunyomi: "き (ki)" },
    { kanji: "本", meaning: "book, origin", onyomi: "ほん (hon)", kunyomi: "もと (moto)" },
    { kanji: "水", meaning: "water", onyomi: "すい (sui)", kunyomi: "みず (mizu)" },
    { kanji: "火", meaning: "fire", onyomi: "か (ka)", kunyomi: "ひ (hi)" },
    { kanji: "父", meaning: "father", onyomi: "ふ (fu)", kunyomi: "ちち (chichi)" },
    { kanji: "母", meaning: "mother", onyomi: "ぼ (bo)", kunyomi: "はは (haha)" },
    { kanji: "耳", meaning: "ear", onyomi: "じ (ji)", kunyomi: "みみ (mimi)" },
    { kanji: "口", meaning: "mouth", onyomi: "こう / く (kou / ku)", kunyomi: "くち (kuchi)" },
    { kanji: "休", meaning: "rest", onyomi: "きゅう (kyuu)", kunyomi: "やす-む (yasu-mu)" },
    { kanji: "何", meaning: "what", onyomi: "か (ka)", kunyomi: "なに / なん (nani / nan)" },
    { kanji: "入", meaning: "enter", onyomi: "にゅう (nyuu)", kunyomi: "い-る / はい-る (i-ru / hai-ru)" },
    { kanji: "上", meaning: "up, above", onyomi: "じょう (jou)", kunyomi: "うえ / あ-げる (ue / a-geru)" },
    { kanji: "前", meaning: "before, in front", onyomi: "ぜん (zen)", kunyomi: "まえ (mae)" },
    { kanji: "下", meaning: "down, below", onyomi: "か / げ (ka / ge)", kunyomi: "した / さ-げる (shita / sa-geru)" },
    { kanji: "千", meaning: "thousand", onyomi: "せん (sen)", kunyomi: "-" },
    { kanji: "午", meaning: "noon", onyomi: "ご (go)", kunyomi: "-" },
    { kanji: "友", meaning: "friend", onyomi: "ゆう (yuu)", kunyomi: "とも (tomo)" },
    { kanji: "古", meaning: "old", onyomi: "こ (ko)", kunyomi: "ふる-い (furu-i)" },
    { kanji: "名", meaning: "name", onyomi: "めい / みょう (mei / myou)", kunyomi: "な (na)" },
    { kanji: "国", meaning: "country", onyomi: "こく (koku)", kunyomi: "くに (kuni)" },
    { kanji: "女", meaning: "woman", onyomi: "じょ (jo)", kunyomi: "おんな (onna)" },
    { kanji: "外", meaning: "outside", onyomi: "がい (gai)", kunyomi: "そと (soto)" },
    { kanji: "男", meaning: "man", onyomi: "だん / なん (dan / nan)", kunyomi: "おとこ (otoko)" },
    { kanji: "子", meaning: "child", onyomi: "し (shi)", kunyomi: "こ (ko)" },
    { kanji: "学", meaning: "study, learn", onyomi: "がく (gaku)", kunyomi: "まな-ぶ (mana-bu)" },
    { kanji: "生", meaning: "life, birth", onyomi: "せい / しょう (sei / shou)", kunyomi: "い-きる / なま (i-kiru / nama)" },
    { kanji: "小", meaning: "small", onyomi: "しょう (shou)", kunyomi: "ちい-さい (chii-sai)" },
    { kanji: "書", meaning: "write", onyomi: "しょ (sho)", kunyomi: "か-く (ka-ku)" },
    { kanji: "毎", meaning: "every", onyomi: "まい (mai)", kunyomi: "-" },
    { kanji: "先", meaning: "ahead, previous", onyomi: "せん (sen)", kunyomi: "さき (saki)" },
    { kanji: "会", meaning: "meet", onyomi: "かい (kai)", kunyomi: "あ-う (a-u)" },
    { kanji: "万", meaning: "ten thousand", onyomi: "まん / ばん (man / ban)", kunyomi: "-" },
    { kanji: "円", meaning: "yen, circle", onyomi: "えん (en)", kunyomi: "まる-い (maru-i)" },
    { kanji: "出", meaning: "exit, go out", onyomi: "しゅつ (shutsu)", kunyomi: "で-る / だ-す (de-ru / da-su)" },
    { kanji: "分", meaning: "minute, divide", onyomi: "ぶん / ふん (bun / fun)", kunyomi: "わ-ける (wa-keru)" },
    { kanji: "北", meaning: "north", onyomi: "ほく (hoku)", kunyomi: "きた (kita)" },
    { kanji: "半", meaning: "half", onyomi: "はん (han)", kunyomi: "-" },
    { kanji: "南", meaning: "south", onyomi: "なん (nan)", kunyomi: "みなみ (minami)" },
    { kanji: "土", meaning: "soil, earth", onyomi: "ど (do)", kunyomi: "つち (tsuchi)" },
    { kanji: "多", meaning: "many", onyomi: "た (ta)", kunyomi: "おお-い (oo-i)" },
    { kanji: "天", meaning: "heaven, sky", onyomi: "てん (ten)", kunyomi: "あま (ama)" },
    { kanji: "安", meaning: "peaceful, cheap", onyomi: "あん (an)", kunyomi: "やす-い (yasu-i)" },
    { kanji: "少", meaning: "few, little", onyomi: "しょう (shou)", kunyomi: "すく-ない / すこ-し (suku-nai / suko-shi)" },
    { kanji: "店", meaning: "shop", onyomi: "てん (ten)", kunyomi: "みせ (mise)" },
    { kanji: "後", meaning: "after, behind", onyomi: "ご / こう (go / kou)", kunyomi: "あと / うし-ろ (ato / ushi-ro)" },
    { kanji: "手", meaning: "hand", onyomi: "しゅ (shu)", kunyomi: "て (te)" },
    { kanji: "新", meaning: "new", onyomi: "しん (shin)", kunyomi: "あたら-しい (atara-shii)" },
    { kanji: "時", meaning: "time, hour", onyomi: "じ (ji)", kunyomi: "とき (toki)" },
    { kanji: "来", meaning: "come", onyomi: "らい (rai)", kunyomi: "く-る (ku-ru)" },
    { kanji: "東", meaning: "east", onyomi: "とう (tou)", kunyomi: "ひがし (higashi)" },
    { kanji: "校", meaning: "school", onyomi: "こう (kou)", kunyomi: "-" },
    { kanji: "気", meaning: "spirit, energy", onyomi: "き (ki)", kunyomi: "-" },
    { kanji: "白", meaning: "white", onyomi: "はく (haku)", kunyomi: "しろ (shiro)" },
    { kanji: "百", meaning: "hundred", onyomi: "ひゃく (hyaku)", kunyomi: "-" },
    { kanji: "目", meaning: "eye", onyomi: "もく (moku)", kunyomi: "め (me)" },
    { kanji: "社", meaning: "company, shrine", onyomi: "しゃ (sha)", kunyomi: "-" },
    { kanji: "空", meaning: "sky, empty", onyomi: "くう (kuu)", kunyomi: "そら / から (sora / kara)" },
    { kanji: "立", meaning: "stand", onyomi: "りつ (ritsu)", kunyomi: "た-つ (ta-tsu)" },
    { kanji: "聞", meaning: "hear, ask", onyomi: "ぶん (bun)", kunyomi: "き-く (ki-ku)" },
    { kanji: "花", meaning: "flower", onyomi: "か (ka)", kunyomi: "はな (hana)" },
    { kanji: "行", meaning: "go", onyomi: "こう / ぎょう (kou / gyou)", kunyomi: "い-く (i-ku)" },
    { kanji: "西", meaning: "west", onyomi: "せい / さい (sei / sai)", kunyomi: "にし (nishi)" },
    { kanji: "見", meaning: "see", onyomi: "けん (ken)", kunyomi: "み-る (mi-ru)" },
    { kanji: "言", meaning: "say", onyomi: "げん (gen)", kunyomi: "い-う (i-u)" },
    { kanji: "話", meaning: "talk, story", onyomi: "わ (wa)", kunyomi: "はな-す (hana-su)" },
    { kanji: "語", meaning: "language", onyomi: "ご (go)", kunyomi: "かた-る (kata-ru)" },
    { kanji: "読", meaning: "read", onyomi: "どく (doku)", kunyomi: "よ-む (yo-mu)" },
    { kanji: "買", meaning: "buy", onyomi: "ばい (bai)", kunyomi: "か-う (ka-u)" },
    { kanji: "足", meaning: "leg, foot", onyomi: "そく (soku)", kunyomi: "あし (ashi)" },
    { kanji: "車", meaning: "car", onyomi: "しゃ (sha)", kunyomi: "くるま (kuruma)" },
    { kanji: "道", meaning: "road, way", onyomi: "どう (dou)", kunyomi: "みち (michi)" },
    { kanji: "金", meaning: "gold, money", onyomi: "きん (kin)", kunyomi: "かね (kane)" },
    { kanji: "長", meaning: "long, leader", onyomi: "ちょう (chou)", kunyomi: "なが-い (naga-i)" },
    { kanji: "間", meaning: "interval, space", onyomi: "かん / けん (kan / ken)", kunyomi: "あいだ / ま (aida / ma)" },
    { kanji: "雨", meaning: "rain", onyomi: "う (u)", kunyomi: "あめ (ame)" },
    { kanji: "電", meaning: "electricity", onyomi: "でん (den)", kunyomi: "-" },
    { kanji: "食", meaning: "eat", onyomi: "しょく (shoku)", kunyomi: "た-べる (ta-beru)" },
    { kanji: "飲", meaning: "drink", onyomi: "いん (in)", kunyomi: "の-む (no-mu)" },
    { kanji: "駅", meaning: "station", onyomi: "えき (eki)", kunyomi: "-" },
    { kanji: "高", meaning: "high", onyomi: "こう (kou)", kunyomi: "たか-い (taka-i)" },
    { kanji: "魚", meaning: "fish", onyomi: "ぎょ (gyo)", kunyomi: "さかな (sakana)" }
  ];